// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/gilcrest/graupel

package graupel

import "time"

// CortexAgent represents a Cortex Agent in Snowflake.
#CortexAgent: {
	// The owner of the agent.
	owner?: null | string @go(Owner,*string)

	// The database name where the agent is located.
	database_name?: null | string @go(DatabaseName,*string)

	// The schema name where the agent is located.
	schema_name?: null | string @go(SchemaName,*string)

	// The name of the agent.
	name?: null | string @go(Name,*string)

	// The comment or description for the agent.
	comment?: null | string @go(Comment,*string)

	// Profile information for the agent.
	profile?: null | #AgentProfile @go(Profile,*AgentProfile)

	// Model to use for orchestration. If not provided, a model is automatically selected.
	models?: null | #ModelConfig @go(Models,*ModelConfig)

	// AgentInstructions contains the various instruction types for the agent.
	instructions?: null | #AgentInstructions @go(Instructions,*AgentInstructions)

	// Orchestration configuration for the agent - currently only budget is supported.
	orchestration?: null | #OrchestrationConfig @go(Orchestration,*OrchestrationConfig)

	// List of tools available to the agent.
	tools?: [...null | #Tool] @go(Tools,[]*Tool)

	// Configuration for each tool used by the agent.
	tool_resources?: {[string]: null | #ToolResource} @go(ToolResources,map[string]*ToolResource)

	// Complete YAML specification for the agent?
	agent_spec?: null | string @go(AgentSpec,*string)

	// Timestamp when the agent was created.
	created_on?: time.Time @go(CreatedOn)
}

#AgentSpec: {
	// Model to use for orchestration. If not provided, a model is automatically selected.
	models?: null | #ModelConfig @go(Models,*ModelConfig)

	// Orchestration configuration for the agent - currently only budget is supported.
	orchestration?: null | #OrchestrationConfig @go(Orchestration,*OrchestrationConfig)

	// AgentInstructions contains the various instruction types for the agent.
	instructions?: null | #AgentInstructions @go(Instructions,*AgentInstructions)

	// List of tools available to the agent.
	tools?: [...null | #Tool] @go(Tools,[]*Tool)

	// Message to return when a tool is unable to answer the user's query.
	tool_unable_to_answer?: null | string @go(ToolUnableToAnswer,*string)

	// Configuration for each tool used by the agent.
	tool_resources?: {[string]: null | #ToolResource} @go(ToolResources,map[string]*ToolResource)

	// Who knows what else might be added in the future
	experimental?: {...} @go(Experimental,map[string]any)
}

// SampleQuestion is a sample question to guide the agent's behavior.
#SampleQuestion: {
	question?: null | string @go(Question,*string)
}

// AgentInstructions contains the various instruction types for the agent.
#AgentInstructions: {
	// Instructions for response generation.
	response?: null | string @go(Response,*string)

	// These custom instructions are used when the agent is planning which tools to use.
	orchestration?: null | string @go(Orchestration,*string)

	// System instructions for the agent.
	system?: null | string @go(System,*string)

	// Sample questions to guide the agent's behavior.
	sample_questions?: [...null | #SampleQuestion] @go(SampleQuestions,[]*SampleQuestion)
}

// AgentProfile is profile information for a Data Cortex agent.
#AgentProfile: {
	// Display name for the agent.
	display_name?: null | string @go(DisplayName,*string)
}

// BudgetConfig specifies time and token budgets for agent operations.
#BudgetConfig: {
	// Time budget in seconds.
	seconds?: null | int @go(Seconds,*int)

	// Token budget.
	tokens?: null | int @go(Tokens,*int)
}

// ExecutionEnvironment  is the configuration for server-executed tools.
#ExecutionEnvironment: {
	// The type of execution environment, currently only warehouse is supported.
	type?: null | string @go(Type,*string)

	// The name of the warehouse. Case-sensitive, if it is an unquoted identifier, provide the name in all-caps.
	warehouse?: null | string @go(Warehouse,*string)

	// The query timeout in seconds
	query_timeout?: null | int @go(QueryTimeout,*int)
}

// ModelConfig specifies the models used by the agent.
#ModelConfig: {
	// Model to use for orchestration. If not provided, a model is automatically selected.
	orchestration?: null | string @go(Orchestration,*string)
}

#OrchestrationConfig: {
	// Budget configuration for orchestration.
	budget?: null | #BudgetConfig @go(Budget,*BudgetConfig)
}

// Tool defines a tool that can be used by the agent. Tools provide specific
// capabilities like data analysis, search, or generic functions.
#Tool: {
	tool_spec?: null | #ToolSpec @go(ToolSpec,*ToolSpec)
}

#ObjectInputParameter: {
	type?:        null | string @go(Type,*string)
	description?: null | string @go(Description,*string)
}

#ArrayInputParameter: {
	type?:        null | string @go(Type,*string)
	description?: null | string @go(Description,*string)
}

// ToolInputSchema represents the schema for tool inputs.
#ToolInputSchema: {
	// The type of the input schema object, e.g., "object", "array", "string", etc.
	type?: null | string @go(Type,*string)

	// A description of what the input is.
	description?: null | string @go(Description,*string)

	// If type is object, definitions of each input parameter
	properties?: {[string]: null | #ObjectInputParameter} @go(Properties,map[string]*ObjectInputParameter)

	// If type is array, the schema for the elements of the array
	items?: null | #ArrayInputParameter @go(Items,*ArrayInputParameter)

	// If type is object, list of required input parameter names
	required?: [...string] @go(Required,[]string)
}

#ToolResource: _

// CortexAnalystTextToSQLToolResource represents configuration for text-to-SQL
// analysis tool. Provides parameters for SQL query generation and execution.
// Exactly one of semantic_model_file or semantic_view must be provided.
#CortexAnalystTextToSQLToolResource: {
	semantic_model_file?:   null | string                @go(SemanticModelFile,*string)
	semantic_view?:         null | string                @go(SemanticView,*string)
	execution_environment?: null | #ExecutionEnvironment @go(ExecutionEnvironment,*ExecutionEnvironment)
}

// CortexSearchToolResource represents Configuration for search functionality.
// Defines how document search and retrieval should be performed.
#CortexSearchToolResource: {
	// The fully qualified name of the search service.
	search_service?: null | string @go(SearchService,*string)

	// The title column of the document.
	title_column?: null | string @go(TitleColumn,*string)

	// The ID column of the document.
	id_column?: null | string @go(IDColumn,*string)

	// Filter query for search results.
	filter: {[string]: [string]: string} @go(Filter,map[string]map[string]string)
}

// GenericToolResource represents a custom function or stored procedure tool.
#GenericToolResource: {
	type?:                  null | string                @go(Type,*string)
	execution_environment?: null | #ExecutionEnvironment @go(ExecutionEnvironment,*ExecutionEnvironment)
	identifier?:            null | string                @go(Identifier,*string)
}

// ToolSpec is the specification of the tool's type, configuration, and input requirements.
#ToolSpec: {
	// The type of tool capability. Can be specialized types like ‘cortex_analyst_text_to_sql’ or ‘generic’ for general-purpose tools.
	type: string @go(Type)

	// Unique identifier for referencing this tool instance. Used to match with configuration in tool_resources.
	name: string @go(Name)

	// Description of the tool to be considered for tool use.
	description?: string @go(Description)

	// JSON Schema definition of the expected input parameters for this tool.
	// This will be fed to the agent so it knows the structure it should follow
	// for when generating the input for ToolUses. Required for generic tools
	// to specify their input parameters.
	input_schema?: null | #ToolInputSchema @go(InputSchema,*ToolInputSchema)
}
